apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
            try_files $uri $uri/ =404;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n\n    root /usr/share/nginx/html;\n    index index.html index.htm;\n\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-config","namespace":"nginx"}}
  creationTimestamp: "2025-01-30T19:51:14Z"
  name: nginx-config
  namespace: nginx
  resourceVersion: "18406"
  uid: 087945f2-1d48-49e9-9262-0e8b14ad0f2b
