apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: "2025-01-30T19:25:26Z"
  generation: 18
  name: nginx-deployment
  namespace: nginx
  uid: fa24ca01-6db6-4464-9241-7ccb09e4b2c3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-config
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-01-30T19:25:26Z"
    lastUpdateTime: "2025-01-30T20:07:24Z"
    message: ReplicaSet "nginx-deployment-54448546" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-08T17:36:33Z"
    lastUpdateTime: "2025-06-08T17:36:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 18
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
