apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: "2025-01-30T19:27:06Z"
  name: nginx-service
  namespace: nginx
  uid: 29f1a3b8-cf34-4dca-a377-fe3e1def609c
spec:
  clusterIP: 10.104.248.255
  clusterIPs:
  - 10.104.248.255
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
